name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
    
    - name: generate token
      run: ./token-generator
